/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 8a3fbe5f30d7510d3d7b78f18f809cca)
interface __BaseEnv_Env {
	FIXR_STATE: KVNamespace;
	WHATSAPP_SENDING_ENABLED: "false";
	NOTIFICATION_COORDINATOR: DurableObjectNamespace<import("./src/index").NotificationCoordinator>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "NotificationCoordinator";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "WHATSAPP_SENDING_ENABLED">> {}
}
